version: "3.9"

services:
  win10:
    image: ghcr.io/vaggeliskls/windows-in-docker-container:latest
    build:
      dockerfile: ./Dockerfile
      context: .
    env_file: .env
    stdin_open: true
    tty: true
    privileged: true
    # runtime: nvidia
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - 3389:3389